# Generated by Django 3.2.12 on 2022-02-16 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_de_Publicacao',
            new_name='data_de_publicacao',
        ),
    ]
